#!/usr/bin/env bash 

msgTag="changevolume"

volume () {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}'
}

muted () {
    res=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d' ' -f3)
    if [[ "$res" == "[MUTED]" ]]; then
        return 0
    else
        return 1
    fi
}


case "$1" in
  "toggle")
      wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    ;;
  "inc")
      wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
    ;;
  "dec")
      wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
      wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    ;;
  *)
esac

if muted; then
    dunstify -a "changevolume" -u low -i audio-volume-muted \
    -h string:x-dunst-stack-tag:$msgTag "静音🔇"
else
    dunstify -a "changevolume" -u low -i audio-volume-high \
    -h string:x-dunst-stack-tag:$msgTag -h int:value:"$(volume)" "音量"
fi
