keys:
  - &jxd_ 30CF6934C4F4E449BEB008BE66F51163C8069D35
  - &jxd_age age1jk6jh5wxv0au84ffhlkd7sd2v3ny8kyxjacvwxtxzgv932c5gf7s76ay8z
  - &server_age age12ccgpfkz5tvz5jyqv5ykqmvg93l0glruexwkclguf3pvg6pegdus4jhavn
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *jxd_age
      - *server_age
