keys:
  - &jxd_ 30CF6934C4F4E449BEB008BE66F51163C8069D35
  - &jxd_age age1jk6jh5wxv0au84ffhlkd7sd2v3ny8kyxjacvwxtxzgv932c5gf7s76ay8z
  - &server_age age12ccgpfkz5tvz5jyqv5ykqmvg93l0glruexwkclguf3pvg6pegdus4jhavn
  - &work_age age1u9gpes0q2qyxzp4h7tdtfwn7mke5gfv68u6qn2ep4k2evcpw4edq2p9yt7
creation_rules:
  - path_regex: secrets/secrets.*?.yaml
    key_groups:
      - age:
          - *jxd_age
          - *work_age
  - path_regex: secrets/work_secrets.yaml
    key_groups:
      - age:
          - *jxd_age
          - *work_age
